settings:
  application:
    env: dev
    envmsg: "谢谢您的参与，但为了大家更好的体验，所以本次提交就算了吧！\U0001F600\U0001F600\U0001F600"
    host: 0.0.0.0
    isinit: true
    jwtsecret: 123abc
    logpath: temp/logs/log.log
    name: go-admin
    port: 8000
    readtimeout: 1
    writertimeout: 2
  database:
    database: dbname
    dbtype: mysql
    host: 127.0.0.1
    password: password
    port: 3306
    username: root
  redis:
    addr: 0.0.0.0:6379
    db: 0
    password: password
    readtimeout: 50
